// chat capability: send one message to Neodrop's conversational agent, wait for
// the reply to finish generating, and return the complete reply.
//
// Flow (everything uses the user's PAT with Bearer auth):
//   1. Create / reuse a session: session.create (global assistant) or
//      session.getOrCreateChannelAssistant (--channel assistant) — tRPC mutation.
//   2. Send: POST /api/chat (a non-tRPC Hono endpoint; the backend has supported
//      PAT Bearer since 2026-07). The response is an SSE stream; the reply is
//      generated by a backend BullMQ worker decoupled from this connection's
//      lifecycle, so the CLI does not parse the stream contents and only treats
//      "the stream reached EOF" as a likely-done signal.
//   3. Settle: poll session.getActiveChatTurn until null (the turn has reached a
//      terminal state — this layer also covers a mid-stream SSE disconnect),
//      then session.getMessages to take the messages added after this user
//      message as the reply. Final consistency relies on getMessages, not the
//      stream.
//
// Why we don't parse the SSE: the UIMessage chunk protocol has many types and
// evolves with the main repo, and the CLI's consumer is an AI agent that wants
// "the complete reply as JSON in one shot", not token-by-token rendering.

import { randomUUID } from "node:crypto";
import { trpcMutation, trpcQuery } from "./api.mjs";
import { note } from "./output.mjs";

const USER_AGENT = "neodrop-cli/1.0 (+https://github.com/NeoDropAI/neodrop-skills)";

function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

// POST /api/chat to send a message. On success returns the Response (the SSE
// stream has started); on HTTP >= 400 it parses the JSON error and throws
// (402 insufficient balance / 401 not logged in / 400 invalid message, etc.).
async function postChatMessage({ apiOrigin, token, sessionId, text, locale, signal }) {
  const url = `${apiOrigin.replace(/\/+$/, "")}/api/chat`;
  const body = {
    sessionId,
    locale,
    message: {
      id: randomUUID(),
      role: "user",
      parts: [{ type: "text", text }],
    },
  };
  const res = await fetch(url, {
    method: "POST",
    headers: {
      "content-type": "application/json",
      "user-agent": USER_AGENT,
      authorization: `Bearer ${token}`,
    },
    body: JSON.stringify(body),
    signal,
  });
  if (res.status >= 400) {
    let payload = null;
    try {
      payload = await res.json();
    } catch {
      // Non-JSON error body; fall back to the HTTP status
    }
    const msg = (payload && (payload.error || payload.message)) || `HTTP ${res.status}`;
    const code = (payload && payload.code) || "";
    throw new Error(code ? `[${code}] ${msg}` : `Send failed: ${msg}`);
  }
  return { response: res, userMessageId: body.message.id };
}

// Read the SSE stream to EOF (contents discarded). A disconnect / timeout is not
// a failure — the backend worker is decoupled from the connection, and the final
// state is settled by polling getActiveChatTurn.
async function drainStream(response) {
  try {
    if (!response.body) return;
    for await (const _chunk of response.body) {
      // Just wait for EOF, don't parse
    }
  } catch {
    note("⚠ SSE connection dropped, falling back to polling for the reply…");
  }
}

// Poll until the session has no live chat turn (the reply has finished /
// failed / been cancelled).
async function pollUntilTurnSettled({ apiOrigin, token, sessionId, deadline, intervalMs }) {
  for (;;) {
    const turn = await trpcQuery({ apiOrigin, token }, "session.getActiveChatTurn", {
      sessionId,
    });
    if (!turn) return;
    if (Date.now() > deadline) {
      throw new Error(
        `Timed out waiting for the reply (turn=${turn.id} still ${turn.status}). You can check the result later with chat history --session ${sessionId}.`,
      );
    }
    await sleep(intervalMs);
  }
}

function extractText(parts) {
  if (!Array.isArray(parts)) return "";
  return parts
    .filter((p) => p && p.type === "text" && typeof p.text === "string")
    .map((p) => p.text)
    .join("");
}

// Noise the raw message payload carries but a CLI consumer never needs: multi-KB
// provider signatures, provider metadata, and per-call execution plumbing.
const NOISE_KEYS = new Set([
  "providerMetadata",
  "callProviderMetadata",
  "resultProviderMetadata",
  "signature",
  "startedAt",
  "finishedAt",
  "durationMs",
  "stepNumber",
  "toolCallId",
]);

function stripNoise(value) {
  if (Array.isArray(value)) return value.map(stripNoise);
  if (value && typeof value === "object") {
    const out = {};
    for (const [k, v] of Object.entries(value)) {
      if (NOISE_KEYS.has(k)) continue;
      out[k] = stripNoise(v);
    }
    return out;
  }
  return value;
}

// Slim a message for output: drop chain-of-thought `reasoning` parts (internal
// thinking, not the answer) and strip the noise keys above from what remains.
export function slimMessage(m) {
  const cleaned = stripNoise(m);
  if (Array.isArray(cleaned.parts)) {
    cleaned.parts = cleaned.parts.filter((p) => p && p.type !== "reasoning");
  }
  return cleaned;
}

/**
 * Send one message and wait for the complete reply.
 *
 * @returns {Promise<{sessionId: string, reply: {text: string, parts: unknown[]} | null, newMessages: unknown[]}>}
 *   reply is the last assistant message among the newly added messages (text =
 *   its text parts joined); in cases such as a failed turn there may be no
 *   assistant reply, so reply is null and the caller decides based on newMessages.
 */
export async function sendAndAwaitReply({
  apiOrigin,
  token,
  sessionId,
  text,
  locale,
  timeoutMs,
  pollIntervalMs,
}) {
  const deadline = Date.now() + timeoutMs;
  const abort = AbortSignal.timeout(timeoutMs);

  // Snapshot existing message ids before sending: the backend assigns the user
  // message its own id (it does not echo the message.id we sent), so we can't use
  // the client id as an anchor — we diff against "messages that appeared after
  // sending".
  const before = await trpcQuery({ apiOrigin, token }, "session.getMessages", {
    sessionId,
  });
  const beforeIds = new Set(before.map((m) => m.id));

  note(`→ Sending to session ${sessionId} …`);
  const { response } = await postChatMessage({
    apiOrigin,
    token,
    sessionId,
    text,
    locale,
    signal: abort,
  });

  note("… generating reply");
  await drainStream(response);
  await pollUntilTurnSettled({
    apiOrigin,
    token,
    sessionId,
    deadline,
    intervalMs: pollIntervalMs,
  });

  const messages = await trpcQuery({ apiOrigin, token }, "session.getMessages", {
    sessionId,
  });
  // All messages added this round (the diff); dropping the user message we just
  // sent leaves this round's reply (assistant text + intermediate artifacts such
  // as tool / data cards).
  const fresh = messages.filter((m) => !beforeIds.has(m.id));
  const lastUserIdx = fresh.map((m) => m.role).lastIndexOf("user");
  const turn = lastUserIdx >= 0 ? fresh.slice(lastUserIdx + 1) : fresh;
  const lastAssistant = [...turn].reverse().find((m) => m.role === "assistant");

  return {
    sessionId,
    // reply.text is the assistant's final text — empty when it only asked a
    // clarifying question via a tool (read newMessages then). The structured
    // content lives in newMessages, so reply carries just the text (no dup).
    reply: lastAssistant ? { text: extractText(lastAssistant.parts) } : null,
    newMessages: turn.map(slimMessage),
  };
}

/** Create a new session (global assistant), or get the channel's assistant session per --channel. */
export async function resolveChatSession({ apiOrigin, token, channelId }) {
  if (channelId) {
    const session = await trpcMutation(
      { apiOrigin, token },
      "session.getOrCreateChannelAssistant",
      { channelId },
    );
    return session.id;
  }
  const session = await trpcMutation({ apiOrigin, token }, "session.create", {});
  return session.id;
}
